spring.application.name=CampusGigs2026

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/campusgigs
spring.datasource.username=campusgigs
spring.datasource.password=campusgigs
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
